### ISSUE TITLE
Cannot configure the detector

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/cmsgemos#125]
confChamber.py crashes with the following error message:
~~~
2017.07.05.14.06
opened connection
Traceback (most recent call last):
  File "/home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/confChamber.py", line 42, in <module>
    biasAllVFATs(ohboard,options.gtx,0x0,enable=False)
  File "/home/GE11COSMICS/Software/DAQ/cmsgemos/gempython/tools/vfat_user_functions_uhal.py", line 247, in biasAllVFATs
    writeAllVFATs(device, gtx, "VCal",        parameters.defaultValues["VCal"       ], mask=mask)
KeyError: 'VCal'
~~~

Command line used:
~~~
confChamber.py -s2 -g0 --shelf=3 --vfatmask=0xF40400 --vt1bump=5 --chConfig=$DATA_PATH/config/chConfig.txt --vfatConfig=$DATA_PATH/config/vfatConfig.txt
~~~

Got this crash on branches `generic-amc-release-v3` and `generic-amc-release-v3-qc8`.

See also http://cmsonline.cern.ch/cms-elog/995069

**Comment by jsturdy** [comment]
What should be written to the as "default" settings should be decided and then both function call and parameter list can be brought into agreement
* Bias settings are currently good candidates, as we write the same value to each chip
* `VCal` if it has an effect on the operation if it has a non-zero setting should be set to 0 (could be otherwise too, just costs an extra transaction)
* Some of the control registers could be rethought
