### ISSUE TITLE
UML diagram for xHAL/RPC integration

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#159]
## Brief summary of issue

Schematic UML of the future xHAL/RPC integration design
Certain methods are added for illustration purposes and might differ from actual implementation, however the interaction and dependencies are correct (although are of course subject to discussion)
![gemhwuml](https://user-images.githubusercontent.com/7428758/31710518-939211d6-b3f5-11e7-976e-a1b8e04f6e36.png)

 
### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

**Comment by jsturdy** [comment]
OK, good, this diagram helps visualize what I see as the main issue I've been trying to drive home, namely we're getting circular
If the `xHAL` blob and `hwDevice` blob weren't separate, then the semantics would be clear, and would align with how I thought our discussion mostly resolved to, modulo some tweaks due to interoperability
* We have several 'hal' (hardware access library) class defining how to communicate with hardware endpoints using some set of register access libraries (`uhal`, `memsvc`)
* We have some hardware interface class which uses the 'hal` semantics to define operations on different hardware objects
* Then we have (probably, it gets integrated into one of the other pieces, or partly in both) a wrapper around the `hal` part to abstract away the differences and provide a common framework for HW access to leverage the `rpc` capabilities of the `Zynq` and yet preserve the host functionality for arbitrary usage.

But now that we have this, as I said before, we should just apply this model to a very simple operation, and clear up the implementation. Trying any number of iterations on the structure

**Comment by mexanick** [comment]
@jsturdy I remember our discussion (although one of the points to have this diagram is to "store" it and share with others). I was thinking about inclusion of the xHAL modules under the gemhardware, but after some thoughts I still find it as a complication and  a sort of _not really neccessary_ thing. But I agree with you, let's try some simple implementation. I'll give an update as soon as I'll prepare the code.

**Comment by mexanick** [comment]
Given said the above, the inclusion of the xHAL stuff into the gemhardware should not be difficult pending resolution of certain CTP7-related things like proper accounting for the gemhardware dependencies, because the xHAL package doesn't bring any new dependencies and is a standalone package at the moment.

**Comment by bdorney** [comment]
With this diagram in mind it seems like what I attempted to put together:

https://github.com/cms-gem-daq-project/cmsgemos/pull/158
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/137

Is not the functionality that is requested.  I can try to flesh out the above PR's and perform the necessary testing with v2b electronics.  However based on an offline discussion with @jsturdy I'm not sure this is the right direction.

How should we proceed?  It's not really clear to me (I believe this has contributed to the above PR's not being as requested).
