### ISSUE TITLE
Configuration DB discussion

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#177]
## Brief summary of issue

Proposed Use Case diagram
![vfat config db](https://user-images.githubusercontent.com/7428758/39533497-7e6fca4e-4e2f-11e8-9c5b-a259eb7045a7.jpg)

Proposed ERD diagram
![gem db erd diagram](https://user-images.githubusercontent.com/7428758/39533554-a41cf398-4e2f-11e8-9a01-2e49a4fce09e.jpg)

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

**Comment by bdorney** [comment]
In the "Use Case Diagram" under the `Update VFAT Chip Settings` why is the only thing listed as:

> New DAC Calibration

Shouldn't we also be listing the other uses cases, for example:

- Update voltage level on comparator (`CFG_THR_ARM_DAC` or `CFG_THR_ZCC_DAC`), and/or
- Update latency setting of the chip, and/or
- Update pulse stretch setting, and/or
- Update preamp gain setting, and/or
- etc...

Perhaps one or two of these additional uses should be added with an "etc..." as the final item.

**Comment by jsturdy** [comment]
Issues #214, #213, #215 created to address various related aspects

**Comment by lmoureaux** [comment]
I have a few questions/remarks.

### 1. XML templates and contents
1. Is there any documentation of the XML format? While I can reverse-engineer most of the structure from the templates, I may not be aware of all restrictions.
1. Is there any comprehensive list of the settings that should be recorded? @bdorney, did you mention two weeks ago that you had this information in slides?

### 2. Architecture
1. What happens when registers are added to/removed from the OH firmware? Can the database schema be updated on the fly? We may want to keep track of firmware versions.
1. Should the contents of C++ classes/DB objects map directly to registers, or could some aspects be abstracted away? eg the channel control register could be unpacked to provide easy access to individual fields. Packing/unpacking would then be done by the `converter`.
1. I am contemplating the possibility of generating the C++ classes from the XML files at configure time. This would make it easier to keep them in sync. The `reader` and `writer` could be generated in the same way. This would require a python script to be run by the `Makefile`, and add a build-time dependency to some `xml` parsing library for python.

### 3. Others
1. What are the target versions of C++, boost, xeres-c++? I see `gcc 4.7` mentioned in the `Makefile`, does it imply that we don't have C++11?
1. Did I miss any library relevant for the [preliminary steps](https://github.com/orgs/cms-gem-daq-project/projects/6#card-14315661)?

**Comment by bdorney** [comment]
Understood that this was discussed privately among @jsturdy @lmoureaux and @mexanick.  Would someone be able to post a summary of this discussion to keep other developers in the loop?

**Comment by lmoureaux** [comment]
The bottom line of the discussion was that I would post a summary in the form of use-case and class inheritance diagrams.

**Comment by lmoureaux** [comment]
Here's the summary. The use case diagram can be found below:
![screenshot_20181115_160634](https://user-images.githubusercontent.com/22327575/48561513-6dfea480-e8f0-11e8-8241-96719dbdba2c.png)
It's very similar to what @mexanick already wrote down, except that I don't show the use case substructure -- the fact that eg viewing a configuration can be done for only AMC (or anything else in the class diagram below) is implicit.
An important point is that the readout for blob creation won't be done using the same interface (between the DB and the software) as loading entries into the DB.

In order to address preliminary #213 (defining the C++ classes that will hold the configuration), we intend to create the following class structure:
![screenshot_20181115_164158](https://user-images.githubusercontent.com/22327575/48563786-5fff5280-e8f5-11e8-9bf7-443fc1b512fd.png)
I didn't insert a `GEMConfigurationObject`class between the various classes and `xdata::Bag` because the latter has everything I'll need to convert from/to DOM. Due to implementation details of `xdata::Bag`, any non-final subclass would need to be templated anyway.

*End of summary, start of implementation details for #213*

---

Most classes would be generated at build time using a Python script, and have inline pairs of `get` and `set` methods for each register (one exception being `VFATChannelConfiguration` for which I'd like to use some `union` that can't be generated). This will be performed by creating a class holding auto-generated properties and methods and leveraging multiple inheritance as follows:
![screenshot_20181115_164301](https://user-images.githubusercontent.com/22327575/48563858-8c1ad380-e8f5-11e8-88c0-40aa327b1ae7.png)
The `*Gen` classes will be abstract (using [this trick](https://stackoverflow.com/a/14631710)) and part of a `details` namespace to avoid accidental misuse.

I'm not sure yet what input I'll provide to the code generator. In an ideal world, I'd process the schema, since it will provide not only the list of fields, but also bounds and type information. Checks could even be added to setter methods. The problem with this approach is that `xsd` can be very complicated and that I couldn't find any Python library to convert it to Python objects. Maybe I could restrict myself to an `xsd` subset and use standard DOM APIs; or I could use a custom, more constrained file format (likely JSON-based) and generate the schema from there. So the choice is between (in dot notation):
```dot
schema -> {header, source, validation}
```
and
```dot
JSON file -> {schema -> validation, header, source}
```
In any case the schemas will be distributed in the package; the JSON files would only live in the repo.

---

I think that I'm ready to start coding now...

**Comment by jsturdy** [comment]
OK, let's see how it starts shaking out
