### ISSUE TITLE
Scan type peculiarities

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#230]
## Brief summary of issue
Needed for the various scan types is a definition of what the various bit fields mean in the output data format; current implementation in `cmsgemos` does the following (the latency script used at `p5` may be different)

#### `RunType`: 4 bits `[59:56]` in `AMC H2`
* normal operations: `1`
* latency data: `2`
* "threshold" data : `3` (possibly redundant with latency, as only one parameter is changing over time in a given scan)
* s-curve data: `4`, new type, two parameters change over the scan: channel and calibration pulse height

#### `RunParams`: 24 bits `[55:32]` in `AMC H2`
* normal operations: `0x00faac`
* individual bits defined as below, may have messed up the associations
##### `RunParam3`: 8 bits `[39:32]` in `AMC H2`,  `[23:16]` in `RunParams` register
* latency data: unused
* "threshold" data : `VT2` value
* s-curve data: calibration pulse height?

##### `RunParam2`: 8 bits `[47:40]` in `AMC H2`,  `[15:8]` in `RunParams` register
* latency data: unused (could store, e.g., MSPL, "threshold, etc.)
* "threshold" data : `VT1` value
* s-curve data: pulsed channel

##### `RunParam1`: 8 bits (TO BE REMOVED) `[55:48]` in `AMC H2`,  `[7:0]` in `RunParams` register
* latency data: latency value
* "threshold" data : unused (could store, e.g., MSPL, "threshold, etc.)
* s-curve data: unused (could store, e.g., MSPL, "threshold, etc.)

### Types of issue
- [x] Discussion (brainstorming for implementation)

**Comment by bdorney** [comment]
In general I think we should *drop* now our VFAT2 lingo and adopt the VFAT3 vocabulary going forward.

Additionally how do we store the parameters a scan was taken with.  I see you've tried to store them in the words themselves in some cases but there are many relevant parameters that do need to be stored to understand results; we don't have enough bits here to do this.

Is there a "scan was taken with config X" link in the DB?  How is config X created?  By writing some config that already exists, or is config X generated just before the scan starts by reading back all stored register values (preferred).

> * "threshold" data : `3` (possibly redundant with latency, as only one parameter is changing over time in a given scan)

If it was removed how would you distinguish different scans that only have one changing parameter?

##### `RunParam3`: 8 bits `[39:32]` in `AMC H2`, `[23:16]` in `RunParams` register
> * latency data: unused

If we perform internal latency scans we may want to have this be the `CFG_CAL_DAC` value the scan was performed with, otherwise `0x0`.

> * "threshold" data : `VT2` value

The front-end works differently; there is no `VT2`.  The comparator has:

- `CFG_THR_ARM_DAC`,
- `CFG_THR_ZCC_DAC`,
- `CFG_SEL_COMP_MODE`,

If `CFG_SEL_COMP_MODE = 0` we are in CFD mode and `CFG_THR_ZCC_DAC` is released on the `ZCC` after the `ARM` comparator is determined the pulse is over `CFG_THR_ARM_DAC`.

If `CFG_SEL_COMP_MODE = 1` the `ZCC` is not used and only `CFG_THR_ARM_DAC` matters.

This could store `CFG_THR_ARM_DAC` and leave `RunParam2` unused; or we could store `CFG_SEL_COMP_MODE` here and `CFG_THR_ARM_DAC` in `RunParam2`.

> * s-curve data: calibration pulse height?

Sure, `CFG_CAL_DAC`.
 
##### `RunParam2`: 8 bits `[47:40]` in `AMC H2`, `[15:8]` in `RunParams` register
> * latency data: unused (could store, e.g., MSPL, "threshold, etc.)

See discussion under `RunParam1`

> * "threshold" data : `VT1` value
> * s-curve data: pulsed channel
> 

##### `RunParam1`: 8 bits (TO BE REMOVED) `[55:48]` in `AMC H2`, `[7:0]` in `RunParams` register
> * latency data: latency value

This won't work out of the box.  In VFAT3 `SRAM1` (e.g. `CFG_LATENCY`) is a 1024 deep cyclic buffer.  You'll need 10 bits to store the latency.  

Is it possible to reorganise these 24 `RunParam` bits in to make a different word association?  Or simply just use say 2 bits from `RunParam2` and all bits from `RunParam1` to store the latency.  Of the remaining 6 bits of `RunParam2` 3 bits could be used to store `CFG_PULSE_STRETCH`.  

> * "threshold" data : unused (could store, e.g., MSPL, "threshold, etc.)
> * s-curve data: unused (could store, e.g., MSPL, "threshold, etc.)
> 
> ### Types of issue
> * [x]  Discussion (brainstorming for implementation)

**Comment by jsturdy** [comment]
That's a lot of useful information, but what's relevant here is:
* types of scans that will be run using this data path
  * for those, what is changing?
  * what is the size of the range of values that will be scanned?

From this, a format proposal should be easily found.
e.g.,:

#### Latency scan:
* Scans a 10 bit register
* Other configuration parameters (constant for acquisition) that are of interest are (and should be part of the loaded run-time configuration)
  * Pulse stretch
  * Signal can internal (8 bits?)

**Comment by bdorney** [comment]
Following our discussion in the SW dev meeting today we have proposed the following meaning for the 24 bits of the `RUN_PARAMS` register:

<img width="796" alt="RunParams_Definitions_v3" src="https://user-images.githubusercontent.com/6432141/62538697-b92c5f00-b853-11e9-9387-e2544b663d10.png">

Here

- P.S. = `CFG_PULSE_STRETCH`,
- isC = `isCurrentPulse` with 0 (1) = False (True),
- isExtTrig = `isExternalTrig` with 0 representing calibration mode and 1 would be an external trigger; if isExtTrig = 1 and CFG_CAL_DAC = 0 it would imply signals coming from externally injected charge (e.g. from particles in the detector or a signal generator injecting into the VFAT)
- selC = `CFG_SEL_COMP_MODE`; (0x0 = CFD, 0x1 = ARM, 0x2 = ZCC)

We can change the names of these parameters but I think we settled on their meaning in the meeting today.

@jsturdy @mexanick @BenjaminRS @lpetre-ulb @lmoureaux @ram1123.

**Comment by jsturdy** [comment]
Fine with the proposal, latency type it's not an external "trigger", rather, it is **not** an internal pulse, i.e., not a calibration pulse

**Comment by bdorney** [comment]
> Fine with the proposal, latency type it's not an external "trigger", rather, it is **not** an internal pulse, i.e., not a calibration pulse

So we can change `isExtTrig` to `isInt` for `isInternal` and have 1 represent True and 0 represent False.  What do you think?

**Comment by bdorney** [comment]
> <img alt="RunParams_Definitions_v3" width="796" src="https://user-images.githubusercontent.com/6432141/62538697-b92c5f00-b853-11e9-9387-e2544b663d10.png">

Upon further reflection I'm not sure we should use bits `[7:0]` for scurve (`RunType==0x4`) for `CFG_THR_ARM_DAC` since, in the exception of ARM DAC Calibration, this will be unique for every VFAT.

Outstide of `CFG_LATENCY` I'm not sure what we could do with bits `[9:0]` I was also trying to see if we could shift bits 10 and up by 2 to group the other empty bits in `[11:0]` but then I couldn't come up with what to do with those 12 bits beyond again `CFG_LATENCY` as 4 bits is not enough to meaningfully express either:

- L1A period, or 
- Delay between calpulse and L1A.

So not sure how to best use these bits for scurves.

**Comment by jsturdy** [comment]
Originally, the idea was that the secondary variable would be the channel being scanned, however, that is now going to be placed in the chamber header.
I would maybe leave it as is, and have a caveat that for only a DAC calibration will the secondary word be of value (you could then repurpose bit 22 to indicate this, as in the case of the latency scan).
I guess this would tilt that bits `[20:0]` get defined as in one of your earlier proposals, where there's the "primary" scan variable (bits `[9:0]`), and the "secondary" scan variable (bits `[20:13]`)

**Comment by lpetre-ulb** [comment]
Moved to the [GitLab repository](https://gitlab.cern.ch/cmsgemonline/cmsgemos/issues/28).
