### ISSUE TITLE
AMC configuration

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#26]
- why OH manager sets the IE mask, while it is a property of AMC card?
- why we have bunch of constants defined in the GEMFSMApplication.h wihle they are subjected to change? I mean MAX_AMCS_PER_CRATE, MAX_OPTOHYBRIDS_PER_AMC and MAX_VFATS_PER_GEB
- Actually, the MAX_OPTOHYBRIDS_PER_AMC is set to 9 and this contradicts with what's written in gemsupervisor xml config, which makes impossible the proper configuration of the AMC IE mask

**Comment by jsturdy** [comment]
* [input enable mask setting](https://github.com/cms-gem-daq-project/cmsgemos/blob/release-v2-ctp7/gemhardware/src/common/optohybrid/OptoHybridManager.cc#L404)
  * This potentially temporary solution was added so as to not pollute the configuration of the managers with unnecessary information (same reason why every OH info doesn't contain the list of VFATs expected to be present)
  * If the config says an OH board is expected by the manager, it makes perfect sense to have the OH manager responsible for setting that bit high in the input enable mask
  * Basic outline:
   * AMC manager sets mask to 0 on [disableDAQLink](https://github.com/cms-gem-daq-project/cmsgemos/blob/release-v2-ctp7/gemhardware/src/common/HwGenericAMC.cc#L458)
    *  This is currently not called, so is likely the problem if the number of OH boards changes, but needs to be investigated
   * During configure, the OH manager loops over the boards and finds the connected ones, setting the VFAT parameters and flipping the corresponding bit in the enable mask
  * An alternative could be to send the mask from the OH manager to the AMC manager once all boards have been accounted for, so this can possibly be a future solution if this turns out to actually be an issue
* [constants](https://github.com/cms-gem-daq-project/cmsgemos/blob/release-v2-ctp7/gembase/include/gem/base/GEMFSMApplication.h#L31)
  * These are not really going to change, once we have the final firmware the max OH boards will be set
  * They may move into a standalone include file with some generic GEM enums and such
  * This being said, I'm very open to a more dynamic configuration not involving looping, but ensuring no overlapping; the current solution was the simplest to "get it working"
  * That this isn't reflected in some xml files is not a problem, especially as this branch is highly developmental, though I don't understand how it makes it impossible for the OH manager to properly set the mask
  * So what I'm actually concerned about is that the mask isn't being set properly

**Comment by mexanick** [comment]
the masking of VFATs seems to be never called (while the mask has been updated correctly). I added the call and it solved the problem
Considering the constants: I do not object having them in principle, but then two questions are:
* why they are in FSM and not in corresponding managers?
* what is the purpose of have a  "position" parameter for OH in the xml. It should be then computed in the code. The problem I had: I was following the comment in the XML which corresponds to 12 OH per AMC, while the constant in the code was set to 9 and the matching between calculated position and position from XML was screwed,

**Comment by jsturdy** [comment]
* OK, in principle fine, only may want to have an ability to modify the mask read from hardware with an "ignore VFATs" list, which I think I have some placeholders for
* They're defined in the base class of GEMFSMApplication since all others inherit from it, and some of the managers need to know about more than one of the constants
* I would also prefer to get rid of the position, **but**, if sending parameters via SOAP, one needs to know specifically which board they correspond to, and the "position" is the array index in the xoap package
  * Definitely would like to revisit it and improve it if possible
  * The comment was a guideline that never got updated for the hack of having only 9 OH boards
