### ISSUE TITLE
[feaure] Calibration suite UI

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#264]
## Brief summary of issue
Discussion of design of calibration suite UI

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Context
[slides](https://www.dropbox.com/s/b6c654p3t8s36vz/CalibrationInterface.pdf?dl=0)

**Comment by jsturdy** [comment]
### Tracking data scans
#### Slide 1
* The current dropdown has both calibrations as well as simple monitoring (temperature scan?). I would separate these

#### Slide 2
* Common settings for all tracking data scans:
  * Trigger source
    * `Loopback` is not currently applicable (maybe one day if we do a local trigger loopback from AMC to AMC13)
    * `TTC` is really the only option if full tracking data readout is being used
      * Can use AMC13 to generate local triggers
      * Can use optical inputs to AMC13
      * Can use `LEMO/T3` input to AMC13
  * Number of samples
  * Scan min/max
* Settings that are specific for using a generated pulse (whether from the AMC or AMC13)
  * Delay (set on BGO generator)
  * L1A time (set on trigger generator)
  * CalPulse phase (set on chip)
  * MSPL (set on chip)
  * Channel min/max (set on chip, probably only relevant for s-curve)

* For the latency scan, I would also add an option of "signal source", i.e., is the signal coming from a particle, or from a calibration pulse
* What is `Throttle`?
* `V2 Threshold` should be removed

You can either invalidate or hide the settings that are not relevant for each scan, I don't have a strong preference

#### Slide 3
I can't see from the AMC/OH dropdown if there are "select" all for the AMC/OH combinations
*  "select all AMCs" would select all AMCs and all OptoHybrids
*  "select all OptoHybrids" would be a per AMC and select all OptoHybrids on a given AMC
* I would also have a checkbox for each OH, rather than a "mask", which should be abstracted away from the user

#### Slide 8
Trimming is a series of complete s-curves, so can remove some of the selections for this.
It also does an s-bit rate scan, so the desired rate to reach should be provided here (@bdorney can comment)

### Trigger data scans
* There is no trigger source for these, as there is no tracking data to be analyzed

#### Slide 7

#### Slide 11

#### Slide 12

### Other calibrations
* There is no trigger source for these, as there is no tracking data to be analyzed

#### Slide 9
* A list of the DACs to possibly scan should be provided and selectable
* Include a DAC min/max
* Include a number of samples
* certain ranges should be excluded, depending on the DAC to be scanned

### Not scans/calibrations
#### Slide 10
Can @bdorney remind what `monitorTemperatures.py` is used for?
This should go in a monitoring page, right?
Or is it somehow connected to some calibration?

### General comments
#### Display of data
For the non-tracking data, the data will be returned in some text format.  It would be nice to convert it to JSON and then use a JS library to provide simple displays of this in the browser (along with an option of "export", though the output data should *always* be saved somewhere)
* I would prefer that no ROOT be required at this stage, but am open to discussion on this point

**Comment by bdorney** [comment]
# Slide 1

@jsturdy if you separate calibration and monitoring scans how do you provide the user a way to perform these?  Do we foresee to continue to maintain the `vfatqc` repo?  In this case then yes this monitoring scan could be dropped.

# Slide 2

- Drop down list change `Phase Scan` to `GBT Phase Scan`
- Change `S-bit Rate Scan` to `S-bit ARM DAC scan`, we are using the sbits to scan the arming comparator DAC value (e.g. `CFG_THR_ARM_DAC`)
- Change `Threshold DAC Scan` to `ARM DAC Scan`, we are just sending L1A's and looking what the comparator tells us by DAC value (e.g. scanning `CFG_THR_ARM_DAC`)
- Change `Temperature Scan` to `Temperature Monitoring`, nothing is being scanned here.
- Change `DAC trimming` to `Derive Channel Trim Registers`, this is more appropriate to what is actually being done.
- Change `SbitReadOut Scan` to `Readout SBITs`, nothing is being scanned.
- Change `Sbit Map And Rate Scan` to `Check SBIT Mapping and Rate Calculation`, we aren't really scanning a DAC, we are checking to make sure the OH FW is behaving as expected.

@jsturdy This is a `Throttle` to apply to the input trigger rate, I think this is only valid for `ultraLatency.py`.

# Slide 3

- All instances of `pulse length` should be changed to `pulse stretch`, this better matches the register name in VFAT3; this applies to all slides.
   - Additionally all instances of `MSPL` should be changed to `Pulse Stretch`.
- All instances of `v2 threshold` should be replaced with `CFG_THR_ARM_DAC`, this applies to all slides.
- Add units to all fields, units should either be, e.g. `(nevts)`, `(BX)`, `(DAC Units)`, etc...
- Change `L1A time` to `L1A period (BX)` as this is more representative.

# Slide 4

- For the drop down menu, is there a "select all" button? Or can it default to have a certain number of AMC's selected?  For a particular test stand this shouldn't really change and especially not in P5.
- What happens if I enter an invalid OH mask? e.g. 0xffff, will it know that's invalid or does it rely on the underlying function to raise an error?
- What happens if the calpulse is not being used? e.g. if this is coming from particles from the detector? How is this configured differently?

# Slide 5

- Default Data type to "Tracking" data here.

# Slide 6

Having multiple options for trigger source here doesn't make sense for an scurve.  This should come from the AMC13's trigger generator (TTC) in local mode.  See @jsturdy's comment on trigger sources.

# Slide 7

- Default scan-per-channel to false, otherwise it will take 10.5 hours per scan :D
- Remove `trigger source` from this page entirely.  This doesn't take a trigger, it reads counters of the trigger data the VFAT3's are sending the OH.
- The `VFAT channel` options should only display when scan-per-channel is true; otherwise a channel number of 128 needs to be sent to the calling function to tell the code to take the OR of all channels on the VFAT.

# Slide 8

With regard to @jsturdy's comments I think I would keep the following items:

- Number of samples
- L1A time
- Latency
- Pulse Delay
- MSPL (re-labeled as "Pulse Stretch")

But V1 Threshold should be dropped and in this regard the interface should be redesigned. The trim settings are only valid only around the ARM DAC setting they were derived at plus some order epsilon.  So if you trim at an ARM DAC setting of 100 for all VFATs those settings are only valid around that DAC value.  

Also I don't think the scan should do a "sbit threshold scan" at the start.  This is prone to error since all channel registers will be zero'd and the sbit threshold scan would take the OR of all channels on a VFAT; if there's one or more hot channels (likely) this would dominate the rate and shift the ARM DAC value to an artificially high value. Ideally we would want to either have a configuration look-up that we trim around; e.g. a DB query is perfromed and the operator can select "trim at some configuration that is known".  This can either be a set of ARM DAC values for each VFAT on each OH in OH mask, or it can be a list of set thresholds in terms of charge we want to set the threshold at (it's the same really).  In each case some DB interaction is expected.  We cannot just use one fixed value of ARM DAC for all VFATs on all OH's in ohMask.

If we want the trim to make a fresh new configuration, and not use a pre-existing one, then it should first do an scurve, analyze the scurve, mask hot channels found, then do the sbit threshold scan, then use a specified threshold for noise (e.g. 1 Hz, 0 Hz?), and then it would take the trim run.  This however would require the operator has set the HV such that dV_GEMs = 0 but all other fields are non-zero (otherwise the determination of when the noise goes below the defined rate is not accurate).

No matter what a DB interaction is required, since you need to know:

1. The calibration coefficients for the `CFG_CAL_DAC` of each VFAT, and
2. The calibration coefficients for the `CFG_THR_ARM_DAC` of each VFAT.

Last comment, the `Trim values` are interpreted as what?  You need at least three points for this to work successfully and they need to span the DAC range, e.g. the set {-63,0,63} should be the default.  Additionally values could be added but those three are the *bare minimum*.

# Slide 9

- The "Trigger Source" block should be removed.  There is no trigger being sent here.  The ADC in the VFAT has it's own state machine that causes data to be queried and stored; it's independent of any L1A source from the backend.
- You should have a drop down menu for which DAC's to scan which should default to "all".  The list of possible DACs are shown [here](https://github.com/cms-gem-daq-project/cmsgemos/blob/1ce5090a824a6109424862e8dbc03dfd32c4f70f/gempython/tools/amc_user_functions_xhal.py#L14-L40).
- The VFAT3 has two ADC's called ADC0 (internally referenced) and ADC1 (externally referenced).  There should be a setting to switch between them, like: `ADC: Internal, External` like you have the orange boxes for the other parameters with radio buttons.

# Slide 10

- Change `Temperature Sensor` to `VFAT3 Temperature Sensor` and default this to `Internal`.  The VFAT3 team have shown the internal sensor is more reliable.  The other devices that have a temperature monitoring (e.g. the OH) does not have the possibility to choose which sensor to monitor the temperature with.
- Change `Time interval(s)` to `Interval Between Measurement (s)` as this is what is actually done.

# Slide 11

- Here the trigger source is *optional*, the readout occurs regardless of whether an L1A is sent or not,
    - Only TTC or TTC using the LEMO/T3 would be meaningful here (See @jsturdy's comment on trigger sources).
    - Here the L1A is just used to determine the time between the SBIT and the L1A

# Slide 12

- Here the trigger source is meaningless; there is no L1A that is being sent.
- Need units on the rates; the defaults are kHz or Hz?  If Hz the defaults are *way too low*.

# Missing Routing: Calibrate `CFG_THR_ARM_DAC`

We need an interface for calibrating the ARM DAC.  This should would basically launch a set of scurves each at a different `CFG_THR_ARM_DAC` value.  So I would expect this interface to follow from the Scurve scan interface on slide 6 with the following changes:

- VFAT channel Min and VFAT channel Max fields are removed,
- Trigger source is removed as it doesn't make sense for this to be configurable
- Add a "list of ARM DAC settings to Scan" field, this could default to: {20,25,30,40,50,60,70,80,100,125,150,175}

# General Comments

>For the non-tracking data, the data will be returned in some text format. It would be nice to convert it to JSON and then use a JS library to provide simple displays of this in the browser (along with an option of "export", though the output data should always be saved somewhere)

> - I would prefer that no ROOT be required at this stage, but am open to discussion on this point

For the non-tracking data why not just have it return in a text format compatible with `TTree::ReadFile()` and follow the current GEM Tree structure for those scans.  This would require minimal changes to the analysis tools.  This decouples ROOT and uses text output.  I think this is a good compromise.

For those analysis tools that are not multi link I would have one text file be generated per (AMC,OH) pair.  This then allows minimal changes to the analysis tools.

**Comment by jsturdy** [comment]
> @jsturdy if you separate calibration and monitoring scans how do you provide the user a way to perform these? Do we foresee to continue to maintain the `vfatqc` repo? In this case then yes this monitoring scan could be dropped.

My primary point here was that a "monitoring scan", as best I understand it (and I have no idea what a "scan" of some monitor data really is), is not calibration related at all, and rather should be in some monitoring framework

**Comment by bdorney** [comment]
Based on discussion in the meeting this morning @jsturdy and I agreed to remove the "Temperature Scan" from the UI.

**Comment by mexanick** [comment]
ok, thanks guys for your feedbacks. I have a question: while we certainly can provide the interface labels based on @bdorney's suggestions, won't it'll be better to use the labels equal to or very similar to the param names in the RPC? This simplifies a bit the design on one hand and streamline the understanding of what's passed where from interface to embedded backend for future developments... E.g. we have a variable `mspl`- let's use it for label and everywhere... let me know what you think.

**Comment by bdorney** [comment]
I guess there’s two philosophies here:

1. What’s easier for the developer (which is for sure what your proposal will be), and
2. What’s easier for the end user (which I think is what I was shooting for)

Additionally I have specifically been trying to remove historic v2b electronics terminology which will for sure reduce confusion in the future.  I would favor this approach but if there is a *strong* reason against it (or against working toward it) I’ll relent.

**Comment by mexanick** [comment]
I'm all in about removing the v2 remnants. But i think it would ease the communication between users and developers if we have settings labels equal to an actual register name. And if the reg name is not reflecting its meaning, I would change it.

On Mar 26, 2019 13:02, Brian Dorney <notifications@github.com> wrote:

I guess there’s two philosophies here:

  1.  What’s easier for the developer (which is for sure what your proposal will be), and
  2.  What’s easier for the end user (which I think is what I was shooting for)

Additionally I have specifically been trying to remove historic v2b electronics terminology which will for sure reduce confusion in the future. I would favor this approach but if there is a strong reason against it (or against working toward it) I’ll relent.

**Comment by mexanick** [comment]
Obsolete. Has been implemented
