### ISSUE TITLE
Object removal/redefinition

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#270]
## Brief summary of issue
While going through the cleanup of the `Hw<Device>` interfaces, I'm cleaning out some obsolete/V2 only functionality.
Some of these are "link" status/reset functions, which were getting link error counters, and resetting these counters.
Probably these are mirrored in some (number of) other functions currently, and as a default I'm just going to drop them from the current version (they can be readded later)
The benefit of these structures was that one could have an easy interface to a link status object and have an `isGood` function defined on the member values.

```c++
-      typedef struct OpticalLinkStatus {
-        uint32_t GTX_TRK_Errors  ;
-        uint32_t GTX_TRG_Errors  ;
-        uint32_t GTX_Data_Packets;
-        uint32_t GBT_TRK_Errors  ;
-        uint32_t GBT_Data_Packets;
```

These had no direct analog in the V3 FW and were mapped to:
```c++
-  if (linkCheck(gtx, "Link status")) {
-    linkStatus.GTX_TRK_Errors   = readReg(getDeviceBaseNode(),toolbox::toString("OH_LINKS.OH%d.TRACK_LINK_ERROR_CNT", gtx));
-    linkStatus.GTX_TRG_Errors   = readReg(getDeviceBaseNode(),toolbox::toString("TRIGGER.OH%d.LINK0_MISSED_COMMA_CNT",gtx));
-    linkStatus.GTX_Data_Packets = readReg(getDeviceBaseNode(),toolbox::toString("OH_LINKS.OH%d.VFAT_BLOCK_CNT",       gtx));
-    linkStatus.GBT_TRK_Errors   = readReg(getDeviceBaseNode(),toolbox::toString("OH_LINKS.OH%d.TRACK_LINK_ERROR_CNT", gtx));
-    linkStatus.GBT_Data_Packets = readReg(getDeviceBaseNode(),toolbox::toString("OH_LINKS.OH%d.VFAT_BLOCK_CNT",       gtx));
-  }

```

Also removed from the `HwOptoHybrid` are all of the `IPBus` counters related to the various requests/replies on each link.  I don't think there is an equivalent in V3 FW, so they are being dropped entirely.

This issue is just to have a discussion on what, if any, information should be a member of the `Hw<Device>` class itself, in terms of core functionality going forward.

### Types of issue
- [x] Change notices (notification of change which removes functionality)

**Comment by bdorney** [comment]
# GTX_TRG_Errors

I guess this would keep the `GTX_TRG_Errors` since it's driven by the OH FPGA via the VTTx's.

I think it's not true to say there's no direct analog in v3 FW, for the case of `linkStatus.GTX_TRG_Errors` this is directly relatable to v3 FW.  See for example the [getmonTRIGGEROHmain](https://github.com/cms-gem-daq-project/ctp7_modules/blob/a7b0b98b4ffad8c76ff698a4f3b6bcf6b6e4cac0/src/daq_monitor.cpp#L125-L146) and [getmonTRIGGEROHmainLocal](https://github.com/cms-gem-daq-project/ctp7_modules/blob/a7b0b98b4ffad8c76ff698a4f3b6bcf6b6e4cac0/src/daq_monitor.cpp#L72-L123) which query, among other registers, `GEM_AMC.TRIGGER.OH%d.LINK0_MISSED_COMMA_CNT`.

Note that here we should probably *also* check `LINK1_MISSED_COMMA_CNT` since from what I understood from @evka85 the Virtex7 in the CTP7 (and I guess also the CSC-TMB) rely on the logic and of the two trigger links so if one link is bad the whole trigger is bad.

# GBT_TRK_Errors

I think the tracker link could look at:

1. the `OH_LINK.OHX.GBT_*` registers , specifically those shown under [GBT Ready Registers](https://github.com/cms-gem-daq-project/sw_utils/blob/develop/v3ElectronicsUserGuide.md#gbt_ready-registers), and
2. The VFAT link registers.

These can be queried in a single RPC call using [getmonOHLink](https://github.com/cms-gem-daq-project/ctp7_modules/blob/a7b0b98b4ffad8c76ff698a4f3b6bcf6b6e4cac0/src/daq_monitor.cpp#L294-L317).  Or if compartmentalization is required at the cost of an additional RPC call you can call separately [getmonGBTLink](https://github.com/cms-gem-daq-project/ctp7_modules/blob/a7b0b98b4ffad8c76ff698a4f3b6bcf6b6e4cac0/src/daq_monitor.cpp#L271-L292) and [getmonVFATLink](https://github.com/cms-gem-daq-project/ctp7_modules/blob/a7b0b98b4ffad8c76ff698a4f3b6bcf6b6e4cac0/src/daq_monitor.cpp#L790-L811).

# GBT_Data_Packets

Calling the `getmonOHLink` or `getmonVFATLink` RPC methods above will also return the `DAQ_CRC_ERROR_CNT` register for each VFAT on each OH.  In addition to these counters there is also a CRC error counter for the slow control packets:

```
eagle60 > doc GEM_AMC.SLOW_CONTROL.VFAT3.CRC_ERROR_CNT
Name: GEM_AMC.SLOW_CONTROL.VFAT3.CRC_ERROR_CNT
Description: Number of CRC errors in the VFAT3 slow control reply packets
Address: 0x00b04000
Permission: r
Mask: 0x0000ffff
Module: False
Parent: GEM_AMC.SLOW_CONTROL.VFAT3
None
```

But this is a single register and it's for the entire AMC so it can probably be just queried with `uhal`.

**Comment by cgalloni** [comment]
@dteague do you know if these changes were implemented in the code?

**Comment by dteague** [comment]
@cgalloni, as per @lpetre-ulb, The `GTX_TRK_Errors`, `GTX_TRG_Errors`, and `GBT_TRK_Errors` are now implemented by the `GEM_AMC.TRIGGER.OH#.LINK#` and `GEM_AMC.OH_LINKS.OH#.GBT#_*`, as alluded to by in Brian's comment. We can certainly clean up these values by combining them into some useful way in the XDAQ, but all the information is available to the daq_monitor, so I think we can close this issue
