### ISSUE TITLE
[feature] Send calibration parameters to manager applications

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#278]
## Brief summary of issue
In order to have the hardware receive correct scan configuration, the parameters need to be sent from the `CalibrationSuite` to the appropriate `<HW>Manager` applications.

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
This can happen by doing the following:
* Define a `CalibrationParameters` object in `CalibrationSuite`
  * Should contain `xdata::<Type>` objects (see, e.g., [`OptoHybridManager.h`](https://github.com/cms-gem-daq-project/cmsgemos/blob/feature/gemcalib/gemhardware/include/gem/hw/optohybrid/OptoHybridManager.h#L64-L93)
* Define a SOAP callback in the manager applications `xoap::bind()`, (see, e.g., [`GEMSupervisor`](https://github.com/cms-gem-daq-project/cmsgemos/blob/1fdff44b5089203c526de06419de766c46cddd1b/gemsupervisor/src/common/GEMSupervisor.cc#L65) [and](https://github.com/cms-gem-daq-project/cmsgemos/blob/1fdff44b5089203c526de06419de766c46cddd1b/gemsupervisor/src/common/GEMSupervisor.cc#L1291-L1370))
  * This callback should parse the calibration parameters object and set the necessary ones in the manager
    * For a first test, you can print out the parameters received in the manager log message
* From the `CalibrationSuite` send the SOAP message to the appropriate application(s) using: [`gem::utils::soap::GEMSOAPToolBox::sendCommandWithParameterBag`](https://github.com/jsturdy/cmsgemos/blob/subfeature/hw-db-interface/gemutils/src/common/soap/GEMSOAPToolBox.cc#L344-L434)
  * You will have to translate the `CalibrationParameters` into the appropriate type for serialization (it *may* be possible to do this as an `xdata::Bag` object)

**Comment by cgalloni** [comment]
Expected behavior

Upon pressing "apply" button on the Calibration User Interface [applyAction](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L78) optical link mask and calibation parameters are retrieved from the UI

- Then depending on the calibration type ( VFAT DAC scan or not) two kinds of messages are prepared and sent [here](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L167)
- In the case of the normal calibration different maps of the appropriate data types are initialized and filled with the calibration integer and string parameters [initialized](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L316 ) and  the optical link masks [filled](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L327).
- This maps are then used to fill an unorderd map of serializeable [fill](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L328) that are sent to the GLIB manager via a [SOAP message](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L331) . 
- Similar thing for the DAC scans: https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemcalibration/src/common/Calibration.cc#L340  

On the GLIB Manager side:

- Similarly to the Calibration suite, a set of the calibration [parameters](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemhardware/include/gem/hw/glib/GLIBManager.h#L174) is defined as well as the optical link [masks](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemhardware/include/gem/hw/glib/GLIBManager.h#L278).
- Upon the SOAP message arrival the [calibrateAction](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemhardware/src/common/glib/GLIBManager.cc#L799) intilialises the retrieval of the amc optical link masks and the calibration type.
- Then depending on the calibration type the all the other parameters are retrieved in the case of DAC [scans](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemhardware/src/common/glib/GLIBManager.cc#L821) and the other [calibrations](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemhardware/src/common/glib/GLIBManager.cc#L837).


At this point all the parameters are retrieved and ready to be used to configure the detector.

**Comment by jsturdy** [comment]
Hi @cgalloni, sorry for the slow reply.  I'll try to make a few comments here, but my overall comment is going to be: let's focus on the tracking data type scans, since these are the ones where we will benefit from the integration, the speed of the other scans, I believe (@bdorney should remind us), will not significantly be changed by integrating them into this framework, because they are still only doing various register read actions.

#### `Calibration`
On the `Calibration` side, I think things are mostly OK, one caveat would be in *how* we eventually set up to run, i.e., I expect that the `GLIBManager` (or future equivalent) will be per shelf, so we'll have to think about how to address this, but it's a solvable future problem.

#### `GLIBManager`
Overall, I don't like what's been implemented in the `GLIBManager`, and I'll try to outline why.

##### Calibration configuration(s)
> * Similarly to the Calibration suite, a set of the calibration [parameters](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gemhardware/include/gem/hw/glib/GLIBManager.h#L174) is defined as well as the optical link masks.

I didn't like this implementation in the calibraiton suite, but didn't have a better proposal.
Here, this absolutely can't be implemented this way.  My initial suggestion was to create an `xdata:Bag` to hold the set of possible parameters, as well as the "type"; but I know we discussed that sending the `xdata:Bag` in a `SOAP` message wasn't straightforward, so converting to an `std::unordered_map` was suggested.
However, let's keep the class object in `GLIBManager` an appropriately structured `xdata::Bag`, and populate the values in the method that is bound to the `SOAP` callback where the parameters are sent.

##### SOAP helpers
The various `SOAP` helper functions should be implemented in the `GEMSOAPToolBox` class


We can probably sit together after the dev meeting and work through most of these things

**Comment by cgalloni** [comment]
Hi Jared, thanks for the feedbacks. I'm available tomorrow after the meeting to discuss.

**Comment by cgalloni** [comment]
As agreed, now the focus is only on tracking data scans. 

[STILL THE  SAME as in previous comment] 
Upon pressing "apply" button on the Calibration User Interface, the applyAction retrieves optical link mask and calibation parameters from the UI.
In the case of the normal calibration different maps of the appropriate data types are initialized and filled with the calibration integer and string parameters initialized and the optical link masks filled.
This maps are then used to fill an unorderd map of serializeable fill that is sent with a call to the GLIB manager via a SOAP message. 

[NEW]
On the GLIB manager, the callback is binded to the [`gem::base::GEMApplication::calibParamRetrieve`](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/src/common/GEMApplication.cc#L319) that fills the parameters in [`m_scanInfo.bag`](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L193). The bag has been extended with other parameters needed for the scans. 
Also the optical links masks are retrieved and stored in the map [`m_amcOpticalLinks`](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L279).
The SOAP functionalites have been all moved to [GEMSOAPTOOLBOX](https://github.com/cgalloni/cmsgemos/tree/gemcalib-cami-fixup-last/gemutils/include/gem/utils/soap).

I have a couple of questions:

- what is the philosophy of having the scanInfo.bag parameters defined as well of variables as the [ones](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L261) ?
- here I hardcoded the number of [shelves](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L281), but this can be moved either to the xml or to some other part of the code if the opticalLinksMask is not needed here.

**Comment by jsturdy** [comment]
> ... that fills the parameters in [`m_scanInfo.bag`](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L193). The bag has been extended with other parameters needed for the scans.

Here I would suggest that some of these are cleaned up:
*  `nTriggers` and `nSamples` are the same thing
* it probably makes sense to group the trigger setup related items: `pulseDelay`, `l1aTime`, `trigType`, and `signalSourceType` (what is this again?), as they could (in the future) potentially be split off into a dedicated bag that is only sent to the trigger setup application (`AMC13Manager` or appropriate TCDS controller)

> The SOAP functionalites have been all moved to [GEMSOAPTOOLBOX](https://github.com/cgalloni/cmsgemos/tree/gemcalib-cami-fixup-last/gemutils/include/gem/utils/soap).

Can the following be templated?
https://github.com/cgalloni/cmsgemos/blob/db97025168c9eefedfc686e7506a63d36e8682eb/gemutils/include/gem/utils/soap/GEMSOAPToolBox.h#L279-L282


> I have a couple of questions:
> 
> * what is the philosophy of having the scanInfo.bag parameters defined as well of variables as the [ones](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L261) ?

I think these can actually be removed... I don't remember why I added them initially

> * here I hardcoded the number of [shelves](https://github.com/cgalloni/cmsgemos/blob/gemcalib-cami-fixup-last/gembase/include/gem/base/GEMApplication.h#L281), but this can be moved either to the xml or to some other part of the code if the opticalLinksMask is not needed here.

Yeah, I don't like the `opticalLinksMask` bit being here...
It could be implemented in the appropriate manager class (probably `GLIBManager`), and the `calibParamRetrieve` could be virtual in the base class such that you can specialize it in the derived class (if needed, by first calling the base implementation, then adding any specialized actions)

Regarding the number of shelves, I would prefer if it is a part of the `Calibration` xml config, then for the stuff downstream of `GEMSupervisor` (currently, the model is that each `<HW Type>Manager` manages the HW of that type connected to a *single* uTCA shelf).  As such, the "number of shelves" isn't a scan parameter, rather, it should be used to have the `Calibration` tool know which managers to send the parameters to.
In principle, the `ohLinksMask` will work the same way: in the current SW, the available OH links are provided by the `OptoHybridManager` xml config and this will need to change to be provided by the configuration itself (or from some UI that will allow dynamic selection, a la, the `CalibrationWebUI`), so actually, using this calibration tool development as a prototype for how best to do that is not a bad thing, just slightly outside the scope of what you were working on.
I'll take over that aspect of things so you can focus, again, solely on the tracking data scan setup and data-taking, so from your point of development, you should work from the assumption that the downstream manager will already know which AMCs/OptoHybrids will need to be enabled before you send the calibration parameters.

**Comment by mexanick** [comment]
Stale? Anyway, irrelevant for the legacy. Suggest to close.
