### ISSUE TITLE
XHAL not found automatically

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/cmsgemos#307]
## Brief summary of issue

I'm not sure if this is an issue of cmsgemos or XHAL, but I run into errors in gemhardware when building current `develop`. I need to add the following to my env to make it work:
```sh
export CPLUS_INCLUDE_PATH=/opt/xhal/include/
export LIBRARY_PATH=/opt/xhal/lib
```
I'm on `gem904daq02`.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

XHAL is found automatically.

## Current Behavior

XHAL is not found.

### Steps to Reproduce (for bugs)

1. `git fetch`
2. `git checkout origin/develop`
3. `make`

## Possible Solution (for bugs)

Switch to CMake :trollface:

## Context

Trying to build.

## Your Environment

* Version used: current `develop`
* Shell used: bash

**Comment by jsturdy** [comment]
Probably you don't have `XHAL_ROOT` set (and possibly other expected environment things, as they have not all been added as defaults in the makefiles)

**Comment by lmoureaux** [comment]
I don't think I added it, indeed. Would you accept a patch to use `/opt/xhal` by default or cause the build to fail with and intelligible error message if `XHAL_ROOT` is wrong (eg if `$XHAL_ROOT/include/xhal/XHALDevice.h` doesn't exist) ?

**Comment by jsturdy** [comment]
I *think* this is something that we added in the `gemcalibration` stuff that @cgalloni is working on, but we definitely  should patch that in and merge that part to `develop` since everything else really depends on it.
It might actually be better to port the changes made in `gembuild` into here as they were partly designed to solve this type of issue in *all* repositories.
I'll look to see what we put in with `gemcalibration` and compare with how things are done in (not yet merged) `gembuild` and make a patch

**Comment by cgalloni** [comment]
Hi, if I remember correctly we had some compatibility issues so to make `gemcalibration` and `gemhardware` work, we had to install the xhal package locally  on `daq04` and add these lines to 
`setup/etc/profile.d/gemdaqenv.sh`: 
```
export XHAL_ROOT=/afs/cern.ch/work/c/cgalloni/cms-gem-daq-proj/cmsgemos/local/opt/xhal
export XHALROOT=$XHAL_ROOT 
```

**Comment by mexanick** [comment]
shall be closed as irrelevant now?

**Comment by lpetre-ulb** [comment]
Indeed, I think it is irrelevant now. Feel free to reopen the issue if it strikes again.
