### ISSUE TITLE
FSM actions refactoring

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#316]
## Brief summary of issue

GEM's are taking way too long to initialize, while configuration is done very promptly (in seconds).
Possible reasons are:
- abundance of hardware accesses during `initializeAction(...)` in various hardware managers
- issues with uHAL address tables 
  - may consider to remove uHAL dependencies for AMC and OH altogether
### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [x] Refactoring request

## Expected Behavior

Should take much less time at the `initializeAction` and in general init+conf step has to take less time

## Possible Solution (for bugs)

Suggestions: 
- Do not touch real hardware during the `initializeAction(...)` apart from creating `rpc` connections. All HW accesses to registers should be postponed till configuration step. 
- Since the single-register access are rare, consider the possibility to avoid invocation of uHAL HW access and move completely to RPC-based functionality
- Further optimizations (out of scope of this issue): provide resource sharing for the RPC connections.
  - At least, share LMDB among different connections
  - Eventually use shared connections to optohybrids (one per AMC)

This issue header will be updated with code snippets proposals. Please post your comments/suggestions below, each subthread will be summarized here as well.

**Comment by jsturdy** [comment]
Should any sort of "HW is connected" check be done during `Initialize`, as is currently the case?
Or why would we want this failure to happen only during the `Configure` transition?
I think DB connections should also be created/opened in this transition, though probably not the request for the blob.

**Comment by mexanick** [comment]
At the moment we are checking all the optohybrids and reading out the VFAT masks. This is 
a) time consuming
b) should actually not fail the initialize step (e.g. at configure step a link reset or hard reset might be performed to restore a lost communication to some vfats for example)
c) other systems actually don't do any HW access at init phase and do it at configure only 
d) we will anyways check the presence of CTP7s as we are going to open the RPC connections at the init stage

**Comment by lmoureaux** [comment]
Noticing that I was assigned, why is it the case? I don't think this is DB-related?

**Comment by lpetre-ulb** [comment]
>       * may consider to remove uHAL dependencies for AMC and OH altogether

Agreed! Maintaining the address tables on both the CTP7 and the DAQ is machine is cumbersome and error prone. Ideally, the RPC call would even abstract what the firmware cannot so that the xDAQ applications don't even know about register names.

>     * Do not touch real hardware during the `initializeAction(...)` apart from creating `rpc` connections. All HW accesses to registers should be postponed till configuration step.
>     * Since the single-register access are rare, consider the possibility to avoid invocation of uHAL HW access and move completely to RPC-based functionality

:+1: 

>       * At least, share LMDB among different connections

The LMDB address table _is_ shared between different processes. Since it is memory-mapped, it does not consume physical memory and relies on the kernel caching capabilities.

>       * Eventually use shared connections to optohybrids (one per AMC)

I believe this is something which should be done. Not only for 'Initialization' speed reasons, but also to prevent as many race conditions as possible, as low as possible into the software stack.

> Should any sort of "HW is connected" check be done during `Initialize`, as is currently the case?
> Or why would we want this failure to happen only during the `Configure` transition?

How would we know which hardware to connect to during the 'Initialization' phase? The hardware to connect to might depend on the actual configuration, i.e., one broken CTP7 could be discarded during some runs.

> I think DB connections should also be created/opened in this transition, though probably not the request for the blob.

:+1:

> At the moment we are checking all the optohybrids and reading out the VFAT masks. This is
> a) time consuming

I think that the most important reason is that you don't have any idea of which OH and VFAT should be checked until you have received the configuration (which should happen during the 'Configuring' step).

> d) we will anyways check the presence of CTP7s as we are going to open the RPC connections at the init stage

But to which CTP7?

> Noticing that I was assigned, why is it the case? I don't think this is DB-related?

~~This is, I believe, a recurrent issue. Assigning many people to an issue doesn't help to divide the work.~~ Still true, but no longer relevant for this issue.

**Comment by mexanick** [comment]
> Noticing that I was assigned, why is it the case? I don't think this is DB-related?

Sorry, added by mistake. The other parties are relevant to this discussion though ;)
