### ISSUE TITLE
Refactor the existing monitoring package to use templated rpc framework

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#336]
Convert the existing RPC calls to templated RPC calls, streamline the parameter passing

### Types of issue
- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)
- [ ] Documentation update

## Need-by date
Apr 22, 2020

**Comment by dteague** [comment]
I have a preliminary commit making the changes to the templated version as seen in the develop branch (i.e. using ` xhal::common::rpc::call`), but after fetching the newest develop branch, the code doesn't compile because of the included `ctp7_modules` files. Is there a certain setup needed to grab this file or does the makefile need to been update or?

**Comment by lpetre-ulb** [comment]
Indeed, a certain setup is required to work with the templated RPC framework. The exact setup depends on the packages installed on the computer you are using and the developments you are targeting. Since the `gemdaqmonitor` package has not yet been updated to the templated RPC, it is possible that the Makfiles have to be fixed as well.

AFAIK, @mexanick and I are the only ones who worked with the templated RPC in `cmsgemos`. I don't know whether it is worth documenting the procedure since we are planning to change the build system this week.

**Comment by dteague** [comment]
Currently I'm testing on the `daq04` machine and the error happens in `gemhardware`, this after I rebased my code to the newest develop branch. After we get this issue resolve, I can give the code a test and open a PR with the changes I've made!

**Comment by lpetre-ulb** [comment]
Okay, in this case you'll need a local installation/clone of `cmsgemos` (of course!), `ctp7_modules` (since you'll be modifying them) and possibly `xhal`(since the `daq04` version may not be up-to-date). The configuration is a bit tricky and is not fully documented. And I'm still not sure whether or not it should be made publicly available in a comprehensive way since we are going to change everything this week...

**Comment by lpetre-ulb** [comment]
[Moved](https://gitlab.cern.ch/cmsgemonline/cmsgemos/issues/13) to the new GitLab project.
